<a href="https://colab.research.google.com/github/mrdbourke/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00 Làm quen với TensorFlow: Các hướng dẫn cơ bản

## TensorFlow là gì?

[TensorFlow](https://www.tensorflow.org/) là một thư viện đầu cuối (end-to-end), mã nguồn mở dành cho học máy để tiền xử lý dữ liệu, lập mô hình dữ liệu và phục vụ mô hình (trao tới tay người khác).

## Tại sao nên sử dụng TensorFlow?

Thay vì xây dựng mô hình học máy và học sâu từ đầu, hãy sử dụng thư viện như TensorFlow, do nó chứa nhiều hàm học máy phổ biến nhất mà chúng ta sẽ cần.

## Chúng ta sẽ tìm hiểu những gì?

TensorFlow rất rộng. Nhưng tiền đề chính rất đơn giản: biến dữ liệu thành số (tensor) và xây dựng các thuật toán học máy để tìm các mẫu trong đó.

Trong notebook này, chúng ta sẽ bao quát một số hoạt động cơ bản nhất của TensorFlow, cụ thể là:
* Giới thiệu về tensor (tạo tensor)
* Nhận thông tin từ tensor (các thuộc tính của tensor)
* Thao tác với tensor (các phép toán với tensor)
* Tensor và NumPy
* Sử dụng @tf.function (cách tăng tốc các hàm Python thông thường)
* Sử dụng GPUs với TensorFlow
* Bài tập thực hành

Lưu ý:
* Ẩn sau đó là nhiều quy ước tự động diễn ra (khi xây dựng mô hình), nắm được điều này rất có ích vì nếu thấy chúng, chúng ta sẽ biết điều gì đang xảy ra.
* Với bất kỳ hàm TensorFlow nào mà bạn gặp, hãy xem lại trong tài liệu, chẳng hạn: mở tài liệu Python API có tất cả các hàm và kiếm điều bạn muốn biết: https://www.tensorflow.org/api_docs/python/ (đừng lo nếu lúc đầu bạn cảm thấy quá sức, cứ thực hành đủ là các bạn sẽ quen với việc vận hành tài liệu thôi).



## Giới thiệu về Tensor

Nếu đã từng sử dụng NumPy, các bạn sẽ thấy [tensors](https://www.tensorflow.org/guide/tensor) giống như mảng NumPy (chúng ta sẽ thấy điều này sau).

For the sake of this notebook and going forward, you can think of a tensor as a multi-dimensional numerical representation (also referred to as n-dimensional, where n can be any number) of something. Where something can be almost anything you can imagine:  Trong notebook này và các notebook sau, có thể coi tensor là một biểu diễn số đa chiều (hay n-chiều, trong đó n là một số bất kỳ) của bất cứ điều gì mà chúng ta nghĩ tới.
* Có thể là chính các số (dùng tensor để thể hiện giá nhà).
* Có thể là hình ảnh (sử dụng tensor để biểu diễn pixel của hình ảnh).
* Có thể là văn bản (sử dụng tensor để biểu diễn từ).
* Hoặc có thể là một dạng thông tin (hoặc dữ liệu) khác cần biểu diễn với số.

Khác biệt chính giữa tensor và mảng NumPy (hay mảng số n-chiều) là tensor có thể dùng trong [GPU (bộ xử lý đồ họa)](https://blogs.nvidia.com/blog/2009/12/16/whats-the-difference-between-a-cpu-and-a-gpu/) và [TPUs (bộ xử lý tensor)](https://en.wikipedia.org/wiki/Tensor_processing_unit).

Việc chạy trong GPU và TPU có ưu điểm là nhanh hơn, tức là chúng ta có thể tìm mẫu trong các biểu diễn dạng số của dữ liệu nhanh hơn qua việc dùng GPU và TPU.

Chúng ta đã đề cập khá nhiều về tensor, hãy xem:

Trước tiên, hãy import TensorFlow dưới alias (bí danh) thường gặp là `tf`.

In [ ]:
!pip install tensorflow --user

  Using cached tensorflow-2.15.0-cp39-cp39-win_amd64.whl (2.1 kB)
  Using cached tensorflow_intel-2.15.0-cp39-cp39-win_amd64.whl (300.8 MB)
  Using cached grpcio-1.60.1-cp39-cp39-win_amd64.whl (3.7 MB)
  Using cached ml_dtypes-0.2.0-cp39-cp39-win_amd64.whl (938 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
  Using cached keras-2.15.0-py3-none-any.whl (1.7 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached gast-0.5.4-py3-none-any.whl (19 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached tensorboard-2.15.2-py3-none-any.whl (5.5 MB)
  Using cached google_auth-2.28.0-py2.py3-none-any.whl (186 kB)
  Using cached google_auth_oauthlib-1.2.0-py2.py3-none-any.whl (24 kB)
  Using cached cachetools-5.3.2-py3-none-any.whl (9.3 kB)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # tìm số phiên bản (nên là 2.x+)

2.15.0


### Tạo Tensors với `tf.constant()`

Như đã đề cập trước đó, chúng ta thường không tự tạo tensor do TensorFlow có các mô-đun đã tích hợp sẵn (như [`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) và [`tf.data`](https://www.tensorflow.org/guide/data)), cho phép đọc các nguồn dữ liệu và tự động chuyển đổi chúng thành tensor, sau đó các mô hình mạng nơ-ron sẽ xử lý giúp chúng ta.

Nhưng giờ, do chúng ta đang làm quen với tensor và cách thao tác, hãy xem chúng ta sẽ tạo ra chúng như thế nào.

Chúng ta sẽ bắt đầu bằng cách sử dụng [`tf.constant()`](https://www.tensorflow.org/api_docs/python/tf/constant).

In [2]:
# Tạo một số vô hướng (tensor bậc 0)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Số vô hướng được coi là một tensor bậc 0 vì nó không có chiều (nó chỉ là một con số).

> 🔑 **Lưu ý:** Hiện tại, chúng ta không cần phải biết quá nhiều về các bậc khác nhau của tensor (nhưng sẽ xem xét về điều này sau). Điều quan trọng là cần biết tensor có phạm vi không giới hạn về chiều (số lượng chính xác sẽ phụ thuộc vào dữ liệu bạn đang biểu diễn).

In [4]:
# Kiểm tra số chiều của tensor (ndim là số chiều)
scalar.ndim

0

In [5]:
# Tạo một vectơ (nhiều hơn 0 chiều)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Kiểm tra số chiều của tensor của vectơ tensor
vector.ndim

1

In [7]:
# Tạo một ma trận (nhiều hơn 1 chiều)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

Theo mặc định, TensorFlow tạo các tensor có kiểu dữ liệu `int32` hoặc `float32`.

Nó được coi là [32-bit precision](https://en.wikipedia.org/wiki/Precision_(computer_science) (số càng cao thì càng chính xác, càng chiếm nhiều dung lượng máy tính)

In [9]:
# Tạo một ma trận khác và xác định kiểu dữ liệu
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # chỉ định kiểu dữ liệu với 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# Mặc dù another_matrix có nhiều số hơn, các chiều của nó vẫn giữ nguyên
another_matrix.ndim

2

In [11]:
# Còn tensor thì sao? (có nhiều hơn 2 chiều, dù tất cả các mục trên đều là các tensor về mặt kỹ thuật)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

Đây là tensor bậc 3 (3-chiều), tuy nhiên, tensor có thể có số chiều bất kỳ (không giới hạn).

Ví dụ: chúng ta có thể biến chuỗi các hình ảnh thành các tensor có shape (224, 224, 3, 32), trong đó:
* 224, 224 (2 chiều đầu tiên) là chiều cao và chiều rộng của hình ảnh tính theo pixel.
* 3 là số kênh màu của ảnh (red, green blue).
* 32 là kích thước batch (số hình mà một mạng nơ-ron thấy tại thời điểm bất kỳ).

Tất cả các biến mà chúng ta vừa tạo thực ra là các tensor. Nhưng các bạn cũng có thể nghe những tên khác (những cái tên mà chúng tôi đặt cho chúng):
* **scalar**: số duy nhất.
* **vector**: số có hướng (ví dụ: tốc độ gió với hướng).
* **matrix**: mảng số 2-chiều.
* **tensor**: mảng số n-chiều (trong đó: n là số bất kỳ, tensor 0-chiều là một số vô hướng, tensor 1-chiều là một vector).

Để tăng nhầm lẫn, thuật ngữ matrix (ma trận) và tensor thường được sử dụng thay thế cho nhau.

Kể từ giờ, khi sử dụng TensorFlow, mọi thứ mà chúng ta đề cập và sử dụng sẽ là tensor.

Để tìm hiểu thêm về khác biệt giữa scalar, vector và matrix, hãy tham khảo [bài viết về visual algebra từ Math is Fun](https://www.mathsisfun.com/algebra/scalar-vector-matrix.html).

![difference between scalar, vector, matrix, tensor](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Tạo Tensor với `tf.Variable()`

Chúng ta cũng có thể (mặc dù rất hiếm vì thường khi làm việc với dữ liệu, tensor sẽ được tạo tự động) tạo tensor bằng cách sử dụng [`tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable).

Sự khác biệt giữa `tf.Variable()` và `tf.constant()` là tensor được tạo bằng `tf.constant ()` là bất biến (không thể thay đổi, chỉ được sử dụng để tạo tensor mới), trong khi đó tensor được tạo bằng `tf.Variable()` có thể thay đổi (có thể thay đổi).

In [13]:
# Tạo tensor tương tự với tf.Variable() và tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

Bây giờ chúng ta hãy thử thay đổi một trong những phần tử có thể thay đổi của tensor.

In [14]:
# Sẽ có lỗi (yêu cầu phương thức .assign())
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

Để thay đổi phần tử của tensor `tf.Variable()`, cần phương thức `assign()`.

In [15]:
# Sẽ không có lỗi
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Giờ hãy thay đổi giá trị trong tensor `tf.constant()`.

In [16]:
# Sẽ có error (không thể thay đổi tf.constant())
unchangeable_tensor[0].assign(7)
unchangleable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Chúng ta sẽ sử dụng cái nào? `tf.constant()` hay `tf.Variable()`?

Điều này còn tùy thuộc xem vấn đề yêu cầu những gì. Tuy nhiên, đa số trường hợp TensorFlow sẽ tự động chọn giúp chúng ta (khi load hoặc mô hình hóa dữ liệu).

### Tạo các random tensor

Random tensor là các tensor có kích thước bất kỳ chứa các số ngẫu nhiên.

Tại sao chúng ta cần tạo random tensor?

Do mạng nơ-ron sử dụng random tensor để khởi tạo trọng số (mẫu) mà chúng ta đang cố tìm hiểu trong dữ liệu.

Ví dụ: quá trình học một mạng nơ-ron thường bao gồm việc lấy một mảng số n-chiều ngẫu nhiên và tinh chỉnh lại cho tới khi chúng biểu diễn một số loại pattern (cách nén để biểu diễn dữ liệu gốc).

**Cách một mạng học**
![how a network learns](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-how-a-network-learns.png)
*Mạng học bằng cách bắt đầu với các pattern ngẫu nhiên (1) rồi qua các ví dụ minh họa của dữ liệu (2) trong khi cố gắng cập nhật các pattern ngẫu nhiên để biểu diễn ví dụ (3)*

Chúng ta có thể tạo random tensor sử dụng lớp [`tf.random.Generator`](https://www.tensorflow.org/guide/random_numbers#the_tfrandomgenerator_class).

In [18]:
# Tạo 2 random tensor (nhưng tương tự nhau)
random_1 = tf.random.Generator.from_seed(42) # thiết lập seed cho khả năng tái tạo
random_1 = random_1.normal(shape=(3, 2)) # tạo tensor từ phân phối chuẩn
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Chúng có như nhau không?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Các random tensor mà chúng ta vừa tạo thực ra là [số giả](https://www.computerhope.com/jargon/p/pseudo-random.htm) (chúng xuất hiện ngẫu nhiên nhưng thực sự không phải như vậy).

Nếu thiết lập seed, chúng ta sẽ nhận được các số ngẫu nhiên (tương tự như `np.random.seed(42)` khi dùng NumPy).

Thiết lập seed, giả sử ""hey, create some random numbers, but flavour them with X" (X là seed).

Các bạn nghĩ điều gì sẽ xảy ra khi ta thay đổi seed?

In [19]:
# Tạo 2 random tensor (khác nhau)
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Kiểm tra các tensor xem chúng có như nhau không
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130817 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

Điều gì sẽ xảy ra nếu chúng ta xáo trộn thứ tự của một tensor?

Chờ đã, tại sao chúng ta lại muốn làm điều đó?

Giả sử chúng ta đang làm việc với 15,000 hình ảnh về mèo và chó, trong đó 10,000 hình ảnh đầu tiên là về mèo và 5,000 hình ảnh tiếp theo là về chó. Thứ tự này có thể ảnh hưởng đến cách mạng nơ-ron học (nó có thể overfit khi tìm hiểu thứ tự của dữ liệu), thay vào đó, chúng ta nên di chuyển dữ liệu xung quanh.

In [20]:
not_shuffled = tf.Variable([[ 3,  4],
                            [ 2,  5],
                            [10,  7]])

In [21]:
# Xáo trộn tensor (có giá trị khi chúng ta xáo trộn dữ liệu)
# Mỗi lần lại lại nhận được các kết quả khác nhau
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [22]:
# Xáo trộn theo thứ tự tương tự mỗi lần sử dụng tham số seed (sẽ không thực sự như nhau)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

Đợi chút...tại sao các số không giống nhau?

Đó là do quy tắc #4 của tài liệu về [`tf.random.set_seed()`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed).

> "4. Nếu cả global seed và operation seed đều được thiết lập: Cả 2 seed được sử dụng kết hợp để xác định trình tự ngẫu nhiên."

`tf.random.set_seed(42)` thiết lập global seed, và tham số `seed` trong `tf.random.shuffle(seed=42)` thiết lập operation seed.

Do "Các phép toán chỉ lệ thuộc vào một random seed thực ra bắt nguồn từ 2 seed: global seed và operation-level seed. Điều này thiết lập global seed."


In [23]:
# Xáo trộn theo thứ tự tương tự mỗi khi

# Thiết lập global random seed
tf.random.set_seed(42)

# Thiết lập operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [24]:
# Thiết lập global random seed
tf.random.set_seed(42) # nếu biến đổi nó thành chú thích, chúng ta sẽ nhận được các kết quả khác nhau

# Thiết lập operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

### Các cách khác để tạo tensor

Mặc dù chúng ta hiếm khi sử dụng chúng (nhớ rằng nhiều thao tác tensor được thực hiện kín đáo cho chúng ta), có thể sử dụng [`tf.ones()`](https://www.tensorflow.org/api_docs/python/tf/ones) để tạo tensor có các giá trị 1 và [`tf.zeros()`](https://www.tensorflow.org/api_docs/python/tf/zeros) để tạo tensor có các giá trị 0.

In [25]:
# Tạo tensor có các giá trị 1
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [26]:
# Tạo tensor có các giá trị 0
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

Chúng ta cũng có thể biến mảng NumPy thành tensor.

Nhớ rằng khác biệt chính giữa tensor và mảng NumPy là tensor có thể chạy trên GPU.

> 🔑 **Lưu ý:** Ma trận hoặc tensor thường được biểu diễn bằng chữ cái in hoa (chẳng hạn `X` hoặc `A`) trong khi vectơ thường được biểu diễn bằng chữ cái in thường (ví dụ: `y` hoặc `b`).

In [27]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # tạo một mảng NumPy từ 1 đến 25
A = tf.constant(numpy_A,
                shape=[2, 4, 3]) # lưu ý: tổng shape (2*4*3) phải khớp với số phần tử trong mảng
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

## Lấy thông tin từ tensor (shape, rank, size)

Sẽ có những lúc chúng ta muốn lấy những thông tin khác nhau từ tensor của mình, cụ thể, chúng ta nên biết những thuật ngữ tensor sau:
* **Shape (hình dạng):** Độ dài (số phần tử) của từng chiều của tensor.
* **Rank (bậc):** Số chiều của tensor. Số vô hướng có rank (bậc) 0, vectơ có rank 1, ma trận có có rank 2 và tensor có rank n.
* **Axis (trục)** or **Dimension (chiều):** Các chiều cụ thể của tensor.
* **Size (kích thước):** Tổng số mục trong tensor.

Chúng ta sẽ đặc biệt sử dụng chúng khi sắp xếp shape của dữ liệu thành shape của mô hình. Ví dụ: đảm bảo shape của image tensor giống với shape của lớp đầu vào mô hình.

Chúng ta đã thấy một trong số chúng trước khi sử dụng thuộc tính `ndim`. Hãy xem các phần còn lại.

In [28]:
# Tạo tensor bậc 4 (4 chiều)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
# Lấy nhiều thuộc tính của tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


Chúng ta cũng có thể lập chỉ mục tensor như Python list.

In [31]:
# Lấy 2 mục đầu tiên của mỗi chiều
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
# Lấy chiều từ mỗi chỉ mục trừ chỉ mục cuối
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
# Tạo tensor bậc 2 (2 chiều)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Lấy mục cuối của mỗi hàng
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

Chúng ta cũng có thể thêm chiều vào tensor mà vẫn giữ thông tin hiện tại bằng cách sử dụng `tf.newaxis`.

In [34]:
# Thêm một chiều bổ sung (vào cuối)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # trong Python "..." nghĩa là "tất cả các chiều trước"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

Chúng ta có thể đạt được điều tương tự khi dùng [`tf.expand_dims()`](https://www.tensorflow.org/api_docs/python/tf/expand_dims).

In [35]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Thao tác tensor (các phép toán với tensor)

Tìm các mẫu trong tensor (biểu diễn dạng số của dữ liệu) cần thao tác với tensor.

Một lần nữa, khi xây dựng mô hình trong TensorFlow, việc khám phá mẫu này sẽ được thực hiện cho bạn.

### Các phép toán cơ bản

Chúng ta có thể thực hiện trực tiếp nhiều phép toán cơ bản trên tensor sử dụng các toán tử của Python như `+`, `-`, `*`.

In [36]:
# Có thể cộng thêm giá trị vào tensor sử dụng toán tử cộng
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

Do chúng ta dùng `tf.constant()` nên tensor ban đầu không đổi (phép cộng được thực hiện trên một bản sao).

In [37]:
# Tensor ban đầu không đổi
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

Các toán tử khác cũng hoạt động.

In [38]:
# Phép nhân (hay phép nhân theo từng phần tử)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [39]:
# Phép trừ
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

Chúng ta cũng có thể sử dụng hàm TensorFlow tương đương. Sử dụng hàm TensorFlow (nếu có thể) có lợi thế là tăng tốc sau đó xuống dòng khi chạy như một phần của [đồ thị TensorFlow](https://www.tensorflow.org/tensorboard/graphs).

In [40]:
# Sử dụng hàm TensorFlow tương đương của toán tử '*' (nhân)
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [41]:
# Tensor ban đầu không đổi
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Phép nhân ma trận

Một trong những phép toán cơ bản nhất của thuật toán học máy là [phép nhân ma trận](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

TensorFlow triển khai chức năng nhân ma trận này theo phương thức [`tf.matmul()`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul).

2 quy tắc nhân ma trận chính cần nhớ là:
1. Các dimension bên trong cần khớp nhau"
  * `(3, 5) @ (3, 5)` sẽ không hoạt động
  * `(5, 3) @ (3, 5)` sẽ hoạt động
  * `(3, 5) @ (5, 3)` sẽ hoạt động
2. Ma trận kết quả có shape của dimension bên ngoài:
 * `(5, 3) @ (3, 5)` -> `(5, 5)`
 * `(3, 5) @ (5, 3)` -> `(3, 3)`

> 🔑 **Lưu ý:** '`@`' là ký hiệu cho phép nhân trong Python.

In [42]:
# Phép nhân ma trận trong TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
# Phép nhân ma trận với toán tử '@' của Python
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

Cả hai ví dụ này đều hoạt động vì biến `tensor` có shape (2, 2).

Điều gì sẽ xảy ra nếu chúng ta tạo ra một vài tensor có shape không khớp?

In [44]:
# Tạo tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Tạo một tensor (3, 2) khác
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [45]:
# Thử nhân ma trận chúng (sẽ có lỗi)
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

Thử nhân ma trận hai tensor có shape `(3, 2)` sẽ gây lỗi vì các dimension bên trong không khớp.

Chúng ta cần thực hiện một trong 2 điều sau:
* Reshape X thành `(2, 3)` để nó là `(2, 3) @ (3, 2)`.
* Reshape Y thành `(3, 2)` để nó là `(3, 2) @ (2, 3)`.

Chúng ta cũng có thể thực hiện một trong 2 điều sau:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - cho phép reshape tensor thành một shape xác định.
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - chuyển chiều của một tensor đã cho.

![lining up dimensions for dot products](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-lining-up-dot-products.png)

Trước tiên hãy thử `tf.reshape()`.

In [46]:
# Ví dụ: reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [47]:
# Thử nhân ma trận với Y đã reshape
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Nếu có tác dụng, hãy thử với `X` đã reshape, trừ việc lần này chúng ta sẽ sử dụng [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) và `tf.matmul()`.

In [48]:
# Ví dụ chuyển vị (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [49]:
# Thử nhân ma trận
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [50]:
# Chúng ta có thể thu được kết quả tương tự với các tham số
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Lưu ý sự khác biệt ở các shape kết quả khi chuyển vị `X` hoặc reshape Y.

Điều này là do quy tắc thứ 2 đã đề cập ở trên:
 * `(3, 2) @ (2, 3)` -> `(3, 3)` được thực hiện với `X @ tf.reshape(Y, shape=(2, 3))`
 * `(2, 3) @ (3, 2)` -> `(2, 2)` được thực hiện với `tf.matmul(tf.transpose(X), Y)`

Loại thao tác dữ liệu này nhắc nhở: chúng ta cần dành nhiều thời gian cho học máy và làm việc với mạng nơ-ron reshape dữ liệu (ở dạng tensor) để chuẩn bị cho việc sử dụng với nhiều thao tác khác (như đưa vào mô hình).

### Tích vô hướng

Nhân các ma trận với nhau còn được gọi là tích vô hướng.

Chúng ta có thể thực hiện thao tác `tf.matmul()` sử dụng [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot).

In [51]:
# Thực hiện tích vô hướng trên X và Y (cần X là chuyển vị)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Các bạn có thể nhận thấy rằng dù sử dụng cả `reshape` và `tranpose` thì chúng ta vẫn sẽ nhận được các kết quả khác nhau khi sử dụng mỗi loại.

Hãy xem một ví dụ, đầu tiên với `tf.transpose()` rồi với `tf.reshape()`.

In [52]:
# Thực hiện phép nhân ma trận giữa X và Y (chuyển vị)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [53]:
# Thực hiện phép nhân ma trận giữa X và Y (rehaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Chúng dẫn đến các giá trị khác nhau.

Điều này thật lạ vì khi xử lý `Y` (ma trận `(3x2)`), reshape thành `(2, 3) và chuyển vị sẽ được shape tương tự.

In [54]:
# Kiểm tra shape của Y, Y đã reshape và Y chuyển vị
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

Nhưng việc gọi `tf.reshape()` và `tf.transpose()` trên `Y` không nhất thiết cho các giá trị tương tự.

In [55]:
# Kiểm tra shape của Y, Y đã reshape và Y chuyển vị
print("Normal Y:")
print(Y, "\n") # "\n" cho dòng mới

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Như các bạn thấy, đầu ra của việc gọi `tf.reshape()` và `tf.transpose()` trên `Y` khác nhau dù chúng có shape tương tự.

Điều này có thể giải thích là do khả vi mặc định của từng phương thức:
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - thay đổi shape của tensor đã cho (đầu tiên) rồi chèn các giá trị theo thứ tự chúng xuất hiện (trong trường hợp của chúng ta: 7, 8, 9, 10, 11, 12).
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - hoán đổi thứ tự của các trục, mặc định trục cuối thành trục đầu, nhưng có thể thay đổi thứ tự bằng cách sử dụng [tham số `perm`](https://www.tensorflow.org/api_docs/python/tf/transpose).

Vậy chúng ta nên sử dụng cái nào?


Một lần nữa, hầu hết thời gian hoạt động (sẽ được thực hiện cho bạn khi chúng cần chạy, chẳng hạn như trong suốt quá trình huấn luyện mạng nơ-ron).

Nhưng nhìn chung, bất cứ khi nào tiến hành phép nhân ma trận và shape của hai ma trận không thẳng hàng, chúng ta sẽ không chuyển vị (không reshape) một trong số chúng để xếp cho chúng thẳng hàng.

### Tidbit: Phép nhân ma trận
* Nếu chúng ta chuyển vị `Y`, nó sẽ được biểu diễn là $\mathbf{Y}^\mathsf{T}$ (lưu ý T là chuyển vị).
* Xem minh họa về phép nhân ma trận từ [Math is Fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html).
* Hãy thử một mô phỏng thực tiễn về phép nhân ma trận: http://matrixmultiplication.xyz/ (như dưới đây).

![visual demo of matrix multiplication](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-matrix-multiply-crop.gif)

### Thay đổi kiểu dữ liệu của tensor

Đôi khi chúng ta cần thay đổi kiểu dữ liệu mặc định của tensor.

Điều này thường xảy ra khi bạn muốn tính toán sử dụng độ chính xác thấp hơn (ví dụ: số thực dấu phẩy động 16 bit với số thực dấu phẩy động 32 bit).

Tính toán với độ chính xác thấp hơn rất hữu ích ở các thiết bị có dung lượng tính toán thấp hơn như thiết bị di động (vì càng ít bit thì càng yêu cầu dung lượng tính toán thấp hơn).

Chúng ta có thể thay đổi kiểu dữ liệu của tensor sử dụng [`tf.cast()`](https://www.tensorflow.org/api_docs/python/tf/cast).

In [56]:
# Tạo tensor mới có kiểu dữ liệu mặc định (float32)
B = tf.constant([1.7, 7.4])

# Tạo tensor mới có kiểu dữ liệu mặc định (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [57]:
# Thay đổi từ float32 thành float16 (giảm độ chính xác)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [58]:
# Thay đổi từ int32 thành float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Lấy giá trị tuyệt đối
Đôi khi chúng ta muốn lấy giá trị tuyệt đối (tất cả các giá trị dương) của các phần tử trong tensor.

Để thực hiện, hãy dùng [`tf.abs()`](https://www.tensorflow.org/api_docs/python/tf/math/abs).

In [59]:
# Tạo tensor có giá trị âm
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [60]:
# Lấy giá trị tuyệt đối
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Tìm min, max, mean, sum (kết tập)

Chúng ta có thể nhanh chóng kết tập (thực hiện phép tính trên toàn bộ tensor) các tensor để tìm giá trị nhỏ nhất, giá trị lớn nhất, giá trị trung bình và tổng của tất cả các phần tử.

Để thực hiện, chúng ta sử dụng phương thức kết tập có cú pháp `reduce()_[action]`, gồm:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - tìm giá trị nhỏ nhất trong tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - tìm giá trị lớn nhất trong tensor (hữu ích khi tìm xác suất dự đoán cao nhất).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - tìm giá trị trung bình của tất cả các phần tử trong tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - tìm tổng của tất cả các phần tử trong tensor.
* **Lưu ý:** mỗi loại này thường nằm trong một mô-đun `math`, chẳng hạn như `tf.math.reduce_min()` nhưng chúng ta cũng có thể sử dụng alias `tf.reduce_min()`.

Hãy xem cách chúng hoạt động.

In [61]:
# Tạo tensor có 50 giá trị ngẫu nhiên trong khoảng 0-100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([85, 71, 20, 49, 71,  1, 73, 47, 82, 31, 49, 40, 84, 29, 36, 74, 56,
       95, 42, 12, 86, 96, 94, 79, 31, 42, 59, 92,  0,  2, 51, 16, 24, 64,
       88, 30, 50, 68,  0, 26, 54, 38, 55, 24, 20, 73, 96, 37,  3, 34])>

In [62]:
# Tìm giá trị nhỏ nhất
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [63]:
# Tìm giá trị lớn nhất
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [64]:
# Tìm giá trị trung bình
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [65]:
# Tìm tổng
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2479>

Chúng ta cũng có thể tìm độ lệch chuẩn ([`tf.reduce_std()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_std)) và phương sai ([`tf.reduce_variance()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_variance)) của các phần tử trong tensor bằng các phương thức tương tự.

### Tìm giá trị lớn nhất và nhỏ nhất theo vị trí

Làm sao để tìm vị trí mà tensor có giá trị lớn nhất?

 Sẽ hữu ích nếu bạn muốn sắp xếp các nhãn (giả sử `['Green', 'Blue', 'Red']`) với tensor xác suất dự đoán (chẳng hạn `[0.98, 0.01, 0.01]`).

Trong trường hợp này, nhãn đã dự đoán (nhãn có xác suất dự đoán cao nhất) là `'Green'`.

Chúng ta có thể thực hiện tương tự với giá trị nhỏ nhất (nếu cần) với các phương thức sau:
* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) - tìm vị trí của phần tử lớn nhất trong tensor đã cho.
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) - tìm vị trí của phần tử nhỏ nhất trong tensor đã cho.

In [66]:
# Tạo tensor có 50 giá trị trong khoảng từ 0 đến 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.11366314, 0.26208686, 0.27826222, 0.02563687, 0.14626333,
       0.57783687, 0.98404165, 0.97321428, 0.11908922, 0.15853911,
       0.72587943, 0.2533579 , 0.16739913, 0.00428706, 0.20297555,
       0.97578399, 0.07452917, 0.45494175, 0.21618069, 0.48074314,
       0.14676879, 0.41193532, 0.09720196, 0.01193251, 0.77980599,
       0.48886689, 0.24947201, 0.51636695, 0.13629582, 0.33077813,
       0.45709903, 0.8833252 , 0.00432469, 0.03849543, 0.86334925,
       0.50218086, 0.60449751, 0.08531771, 0.86943336, 0.96675999,
       0.09991582, 0.82530882, 0.49551516, 0.34964388, 0.62551317,
       0.80527934, 0.92486699, 0.35896475, 0.26134435, 0.66074999])>

In [67]:
# Tìm vị trí phần tử lớn nhất của F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [68]:
# Tìm vị trí phần tử nhỏ nhất của F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [69]:
# Tìm vị trí phần tử lớn nhất của F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 6
The maximum value of F is: 0.9840416494586849
Using tf.argmax() to index F, the maximum value of F is: 0.9840416494586849
Are the two max values the same (they should be)? True


### Nén tensor (loại tất cả các chiều đơn lẻ)

Chúng ta có thể dùng `tf.squeeze()` để loại các chiều đơn lẻ khỏi tensor (chiều có size 1).

* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - loại tất cả các chiều có size là 1 khỏi tensor.


In [70]:
# Tạo một tensor bậc 5 (5 chiều) có 50 số trong khoảng 0-100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [71]:
# Nén tensor G (loại tất cả các chiều 1)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

### Mã hóa One-hot

Chúng ta có thể sử dụng [`tf.one_hot()`](https://www.tensorflow.org/api_docs/python/tf/one_hot) để mã hóa one-hot một tensor gồm các chỉ số.

Chúng ta cũng nên chỉ định tham số `depth` (muốn mã hóa sâu bao nhiêu).

In [72]:
# Tạo một danh sách các chỉ số
some_list = [0, 1, 2, 3]

# Mã hóa one-hot chúng
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Chúng ta cũng có thể chỉ định giá trị cho `on_value` và `off_value` thay vì `0` và `1` mặc định.

In [73]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

### Bình phương, log, căn bậc hai

Chúng ta có thể thực hiện nhiều phép toán khác ở một số giai đoạn.

Chẳng hạn:
* [`tf.square()`](https://www.tensorflow.org/api_docs/python/tf/math/square) - tính bình phương của mọi giá trị trong tensor.
* [`tf.sqrt()`](https://www.tensorflow.org/api_docs/python/tf/math/sqrt) - tính căn bậc hai của mọi giá trị trong tensor. (**lưu ý:** các phần tử phải là kiểu float, nếu không sẽ sai).
* [`tf.math.log()`](https://www.tensorflow.org/api_docs/python/tf/math/log) - tính log tự nhiên của mọi giá trị trong tensor (các phần tử phải là float).

In [74]:
# Tạo tensor mới
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [75]:
# Bình phương nó
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [76]:
# Tính căn bậc hai (không lỗi), không phải là số nguyên
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [77]:
# Đổi H thành float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [78]:
# Tính căn bậc hai
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [79]:
# Tính log (đầu vào cần là float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Thao tác `tf.Variable` tensor

Những tensor được tạo với `tf.Variable()` có thể thay đối tại chỗ với các phương thức sau:

* [`.assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) - gán một giá trị khác cho một chỉ mục cụ thể của tensor variable.
* [`.add_assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) - thêm vào một giá trị hiện có và gán lại nó ở một chỉ mục cụ thể của tensor variable.


In [80]:
# Tạo tensor variable
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [81]:
# Gán cho giá trị cuối cùng một giá trị mới là 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [82]:
# Thay đổi diễn ra tại chỗ (giá trị cuối bây giờ là 50, không còn là 4 nữa)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [83]:
# Thêm 10 vào mỗi phần tử trong I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [84]:
# Một lần nữa, thay đổi diễn ra tại chỗ
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensor và NumPy

Chúng ta đã thấy một số ví dụ về tensor với mảng NumPy như sử dụng mảng NumPy để tạo tensor.

Có thể chuyển đổi tensor thành mảng NumPy bằng:

* `np.array()` - chuyển một tensor để chuyển đổi thành một mảng n-chiều (kiểu dữ liệu chính của NumPy).
* `tensor.numpy()` - gọi một tensor để chuyển thành một mảng n-chiều.

Điều này hữu ích vì nó khiến các tensor lặp lại và cho phép chúng ta sử dụng bất kỳ phương thức NumPy nào trên đó.

In [85]:
# Tạo tensor từ mảng NumPy
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [86]:
# Chuyển đổi tensor J thành mảng NumPy với np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [87]:
# Chuyển đổi tensor J thành mảng NumPy với .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

Theo mặc định, tensor có `dtype=float32`, trong khi mảng NumPy có `dtype=float64`.

Điều này là do mạng nơ-ron (thường được tạo với TensorFlow) có thể hoạt động tốt với độ chính xác thấp hơn (32 bit hơn là 64 bit).

In [88]:
# Tạo tensor từ NumPy và từ một mảng
numpy_J = tf.constant(np.array([3., 7., 10.])) # sẽ là float64 (do NumPy)
tensor_J = tf.constant([3., 7., 10.]) # sẽ là float32 (do mặc định là TensorFlow)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Sử dụng `@tf.function`

Trong quá trình tìm hiểu TensorFlow, chúng ta có thể gặp các hàm Python có decorator [`@tf.function`](https://www.tensorflow.org/api_docs/python/tf/function).

Nếu chưa rõ về Python decorator, hãy đọc [hướng dẫn của RealPython về decorator](https://realpython.com/primer-on-python-decorators/).

Tóm lại, decorator sửa đổi một hàm không bằng cách này thì bằng cách khác.

Trong trường hợp sử dụng decorator `@tf.function`, nó biến hàm Python thành một đồ thị TensorFlow có thể gọi được. Đây là một cách nói hoa mỹ, nếu bạn viết hàm Python của riêng mình và trang bị nó với `@tf.function`, thì khi bạn xuất code (để chạy trên thiết bị khác), TensorFlow sẽ cố chuyển đổi nó thành một phiên bản nhanh (hơn) của chính nó (bằng cách biến nó thành một phần của đồ thị tính toán).

Để biết thêm chi tiết, hãy đọc hướng dẫn [Better performance with tf.function](https://www.tensorflow.org/guide/function).

In [89]:
# Tạo một hàm đơn giản
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [90]:
# Tạo một hàm tương tự và trang bị với tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

Nếu không thấy khác biệt giữa hai hàm trên (hàm được trang bị và hàm không được trang bị) tức là bạn đã đúng.

Phần lớn sự khác biệt xảy ra ẩn sau. Một trong những khác biệt chính là tăng tốc độ code tiềm năng khi có thể.

## Tìm truy cập vào GPU

Chúng ta đã đề cập GPU nhiều lần suốt trong notebook này.

 Vậy làm thế nào để kiểm tra xem chúng ta có sẵn cái nào không?

Chúng ta có thể kiểm tra xem có truy cập vào GPU nào không bằng [`tf.config.list_physical_devices()`](https://www.tensorflow.org/guide/gpu).

In [91]:
!pip install tensorflow

In [92]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Nếu ở trên xuất ra một mảng trống (hoặc không có gì), điều này có nghĩa là chúng ta không có quyền truy cập vào GPU (hoặc ít nhất là TensorFlow không thể tìm thấy nó).

Nếu chạy trong Google Colab, chúng ta có thể truy cập GPU bằng cách vào *Runtime -> Change Runtime Type -> Select GPU* (**lưu ý:** sau khi thực hiện điều này, notebook sẽ khởi động lại và bất kỳ biến nào mà chúng ta đã lưu sẽ bị mất).

Sau khi thay đổi runtime type, chạy cell dưới đây.

In [93]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Nếu truy cập được vào GPU, cell trên sẽ xuất ra như sau:

`[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`

Chúng ta có thể tìm thông tin về GPU của mình bằng `!nvidia-smi`.

In [94]:
!nvidia-smi

Fri Feb 23 08:13:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0              29W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

> 🔑 **Lưu ý:** Nếu chúng ta có quyền truy cập vào GPU, TensorFlow sẽ tự động sử dụng nó bất cứ khi nào có thể.

## 🛠 Bài tập thực hành
> **Lưu ý:** Các bạn cần làm phần bài tập này để chuẩn bị cho phiên review lab.

1. Tạo một vector, scalar, matrix và tensor với các giá trị tùy chọn, sử dụng `tf.constant()`.
2. Tìm shape, rank và size của tensor mà bạn vừa tạo ở 1.
3. Tạo hai tensor chứa các giá trị ngẫu nhiên trong khoảng từ 0 đến 1 có shape `[5, 300]`.
4. Nhân hai tensor mà bạn tạo ở 3, sử dụng phép nhân ma trận.
5. Nhân hai tensor mà bạn tạo ở 3, sử dụng tích vô hướng.
6. Tạo một tensor với giá trị ngẫu nhiên trong khoảng từ 0 đến 1 có shape `[224, 224, 3]`.
7. Tìm min và max của tensor bạn đã tạo ở 6.
8. Tạo một tensor với các giá trị tuyệt đối có shape `[1, 224, 224, 3]` rồi nén nó để thay đổi shape thành `[224, 224, 3]`.
9. Tạo một tensor có shape `[10]` sử dụng các giá trị tùy chọn rồi tìm ra chỉ mục nào có giá trị lớn nhất.
10. Mã hóa one-hot tensor bạn vừa tạo ở 9.

## 📖 Tài liệu tham khảo

* Đọc qua [danh sách TensorFlow Python API](https://www.tensorflow.org/api_docs/python/), chọn một cái mà chúng ta chưa tìm hiểu trong notebook này, thiết kế ngược (tự viết code tài liệu) và tìm hiểu xem nó có tác dụng gì.
* Thử tạo một chuỗi các hàm tensor để tính toán các hóa đơn tạp hóa gần đây nhất (không cần tên các mặt hàng, chỉ cần giá cả ở dạng số).
  * Chúng ta sẽ tính toán hóa đơn tạp hóa theo tháng và năm thế nào khi sử dụng tensor?
* Xem qua hướng dẫn [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) (đảm bảo tự gõ toàn bộ code dù bạn không hiểu nó).
  * Còn hàm nào mà chúng ta sử dụng ở đây khớp với những gì chúng ta sử dụng ở đó không? Những cái nào giống nhau? Những cái nào chúng ta chưa từng thấy trước đây?
* Xem video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - giới thiệu trực quan tuyệt vời về các khái niệm mà chúng ta đã đề cập trong notebook này.

In [95]:
#Tạo một vector, scalar, matrix và tensor với các giá trị tùy chọn, sử dụng tf.constant()
scalar = tf.constant(123)
vector = tf.constant([1, 2, 3, 4])
matrix = tf.constant([[1, 2],
                     [3, 4]])
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                     [1, 4, 6]]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=123>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[7, 8, 9],
         [1, 4, 6]]], dtype=int32)>)

In [96]:
#Tìm shape, rank và size của tensor mà bạn vừa tạo ở 1
print("Shape: ", tensor.shape)
print("Rank: ", tensor.ndim)
print("Size: ", tf.size(tensor))

Shape:  (2, 2, 3)
Rank:  3
Size:  tf.Tensor(12, shape=(), dtype=int32)


In [97]:
#Tạo hai tensor chứa các giá trị ngẫu nhiên trong khoảng từ 0 đến 1 có shape [5, 300]
tensor1 = tf.constant(np.random.rand(1500), shape=[5,300])
tensor2 = tf.constant(np.random.rand(1500), shape=[5,300])
tensor1, tensor2

(<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.44578708, 0.94487377, 0.70534994, ..., 0.54651739, 0.36424597,
         0.18570987],
        [0.92734937, 0.01673906, 0.13931426, ..., 0.90747644, 0.67149372,
         0.55566615],
        [0.7186066 , 0.34884838, 0.11645578, ..., 0.33314822, 0.09479103,
         0.98715888],
        [0.4293929 , 0.5552297 , 0.88862417, ..., 0.86034011, 0.3394354 ,
         0.63541171],
        [0.40259726, 0.39699506, 0.09895032, ..., 0.62075263, 0.69907526,
         0.35305121]])>,
 <tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.49245951, 0.91102894, 0.86554138, ..., 0.84095148, 0.54113956,
         0.78982946],
        [0.40738277, 0.32631571, 0.59460257, ..., 0.00558161, 0.87642063,
         0.58370283],
        [0.12546395, 0.74554529, 0.5950297 , ..., 0.29530454, 0.02130698,
         0.75605566],
        [0.86700914, 0.1604574 , 0.18208236, ..., 0.47529137, 0.71088323,
         0.48114451],
        [0.7127447 , 0.50174837

In [98]:
#Nhân hai tensor mà bạn tạo ở 3, sử dụng phép nhân ma trận.
print(tf.matmul(tensor1, tf.transpose(tensor2)))
print(tf.matmul(tensor1, tf.reshape(tensor2, shape=(300,5))))

tf.Tensor(
[[74.07745464 76.09020841 75.66098798 73.45675974 74.2526823 ]
 [71.52591655 70.29846864 72.64106712 69.26170723 70.72905714]
 [70.83662466 73.62594854 74.61820307 72.63811146 73.76352029]
 [76.60549747 78.16059726 78.71612637 75.99507532 77.16967903]
 [74.8058378  76.54013729 75.99289592 74.85511803 73.24142597]], shape=(5, 5), dtype=float64)
tf.Tensor(
[[72.08195555 77.04943058 74.11884246 71.98678933 72.69370459]
 [69.48956667 72.15679194 73.51990064 70.20003624 68.08313709]
 [73.19437572 75.61139267 75.35601085 75.93848444 74.76436219]
 [75.23170278 78.37273675 78.7111778  75.38038116 77.97721444]
 [70.47274015 76.11296883 76.26526561 72.29628622 74.74412932]], shape=(5, 5), dtype=float64)


In [99]:
#Nhân hai tensor mà bạn tạo ở 3, sử dụng tích vô hướng
print(tf.tensordot(tensor1, tf.transpose(tensor2), axes=1))

tf.Tensor(
[[74.07745464 76.09020841 75.66098798 73.45675974 74.2526823 ]
 [71.52591655 70.29846864 72.64106712 69.26170723 70.72905714]
 [70.83662466 73.62594854 74.61820307 72.63811146 73.76352029]
 [76.60549747 78.16059726 78.71612637 75.99507532 77.16967903]
 [74.8058378  76.54013729 75.99289592 74.85511803 73.24142597]], shape=(5, 5), dtype=float64)


In [100]:
#Tạo một tensor với giá trị ngẫu nhiên trong khoảng từ 0 đến 1 có shape [224, 224, 3]
elements = 224*224*3
tensor3 = tf.constant(np.random.rand(elements), shape=[224,224,3])
tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.38867702, 0.67158286, 0.57116026],
        [0.76442191, 0.23632139, 0.86353411],
        [0.0456306 , 0.23093892, 0.97115247],
        ...,
        [0.08801498, 0.06990825, 0.94694034],
        [0.65103979, 0.85708504, 0.57125453],
        [0.03039579, 0.93315248, 0.89275801]],

       [[0.41390948, 0.72942464, 0.34458307],
        [0.67526339, 0.99641716, 0.60291352],
        [0.81636034, 0.03305277, 0.4131203 ],
        ...,
        [0.95438625, 0.56243061, 0.05326969],
        [0.91569179, 0.42715301, 0.22392387],
        [0.9488083 , 0.99204093, 0.61069109]],

       [[0.29533721, 0.96195384, 0.65089792],
        [0.060729  , 0.66901936, 0.07998047],
        [0.83031484, 0.45933139, 0.61971995],
        ...,
        [0.75142256, 0.27343254, 0.40952594],
        [0.22137119, 0.50266607, 0.82058229],
        [0.32098776, 0.93331295, 0.63382935]],

       ...,

       [[0.63607307, 0.35354671, 0.76190052],
        [0.62

In [101]:
#Tìm min và max của tensor bạn đã tạo ở 6
print(tf.reduce_max(tensor3))
print(tf.reduce_min(tensor3))

tf.Tensor(0.9999992704911664, shape=(), dtype=float64)
tf.Tensor(3.244105861055502e-06, shape=(), dtype=float64)


In [102]:
#Tạo một tensor với các giá trị tuyệt đối có shape [1, 224, 224, 3] rồi nén nó để thay đổi shape thành [224, 224, 3]
tensor4 = tf.abs(tf.constant(np.random.randint(-100,100,elements), shape=[1,224,224,3]))
print(tensor4.shape)
new_tensor4 = tf.squeeze(tensor4)
print(new_tensor4.shape)

(1, 224, 224, 3)
(224, 224, 3)


In [103]:
#Tạo một tensor có shape [10] sử dụng các giá trị tùy chọn rồi tìm ra chỉ mục nào có giá trị lớn nhất
tensor5 = tf.constant(np.random.randint(10, size=10), dtype=tf.int32)
print(tensor5, tensor5.shape)
tf.argmax(tensor5)

tf.Tensor([6 8 5 0 9 3 4 3 7 4], shape=(10,), dtype=int32) (10,)


<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [104]:
#Mã hóa one-hot tensor bạn vừa tạo ở 9
tf.one_hot(tensor5, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>